### PR TITLE
fix: adjust keyboard behavior for iOS using KeyboardAvoidingView

### LINKED ISSUE #41: iOS Keyboard hides buttons when editing wallet
you have to close the keyboard before you can see buttons on the footer of the screen

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #41

## Screenshots

<table>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

### CODE REVIEW

File: pages/receive/Receive.tsx [hunk 1]
```diff
@@ -271,44 +271,46 @@ export function Receive() {
       )}
       {/* TODO: move to one place - this is all copied from LNURL-Pay */}
       {!invoice && enterCustomAmount && (
-        <TouchableWithoutFeedback
-          onPress={() => {
-            Keyboard.dismiss();
-          }}
+        <KeyboardAvoidingView
```
Comment (reneaaron) [inline pages/receive/Receive.tsx:274]: Should we wrap this in a component ourselves to avoid spreading these behaviors across 10s of files maybe? They all look very similar...

**Review by reneaaron — APPROVED** [review]
utACK

File: pages/receive/Receive.tsx (hunk 1 above)
Comment (rolznz) [reply pages/receive/Receive.tsx:274]: I agree, @im-adithya could you do this?

Comment (im-adithya) [reply pages/receive/Receive.tsx]: Done!

File: pages/settings/FiatCurrency.tsx [hunk 2]
```diff
@@ -1,52 +1,49 @@
...
-          <Input
-            autoFocus
-            className="w-full text-center"
-            placeholder="USD"
-            value={fiatCurrency}
-            onChangeText={setFiatCurrency}
-            returnKeyType="done"
-          // aria-errormessage="inputError"
-          />
+    <DismissableKeyboardView>
```
Comment (rolznz) [inline pages/settings/FiatCurrency.tsx:17]: this one is no longer needed, see https://github.com/getAlby/go/pull/113

File: pages/settings/wallets/RenameWallet.tsx [hunk 3]
```diff
@@ -16,11 +17,7 @@ export function RenameWallet() {
     wallets[selectedWalletId].name || ""
   );
   return (
-    <TouchableWithoutFeedback
-      onPress={() => {
-        Keyboard.dismiss();
-      }}
-    >
+    <DismissableKeyboardView>
```
Comment (rolznz) [inline pages/settings/wallets/RenameWallet.tsx:20]: I realized we add this on every page, can it go in `_layout.tsx`?

Comment (im-adithya) [reply pages/settings/wallets/RenameWallet.tsx:20]: Not exactly every page, also not sure if we should add it because we clubbed it with `TouchableWithoutFeedback` and it does Keyboard.dismiss() on press

File: pages/settings/FiatCurrency.tsx (hunk 2 above)
Comment (im-adithya) [reply pages/settings/FiatCurrency.tsx]: Removed ✅

File: pages/settings/wallets/RenameWallet.tsx (hunk 3 above)
Comment (rolznz) [reply pages/settings/wallets/RenameWallet.tsx:20]: ah ok, thanks!

**Review by rolznz — APPROVED** [review]
tACK
