### PR TITLE
fix: handle decimal commas

### LINKED ISSUE #301: Allow decimal commas while entering in fiat
From Discord:
> It would be great to add decimals when trying to create an invoice with fractions while using fiat currencies

Not attaching video due to privacy reasons.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #301

To test:
- Change Number Format in iOS settings to `123,45` (if you are in `123.45`)
- Enter any decimal number after switching to fiat input

### CODE REVIEW

File: components/DualCurrencyInput.tsx [hunk 1]
```diff
@@ -49,23 +50,27 @@ export function DualCurrencyInput({
...
       if (getSatsAmount) {
-        setAmount(getSatsAmount(+text)?.toString() || "");
+        const numericValue = +text.replace(",", ".");
+        setAmount(getSatsAmount(numericValue)?.toString() || "");
       }
     }
   }
 
   function toggleInputMode() {
+    inputRef.current?.blur();
```
Comment (rolznz) [inline components/DualCurrencyInput.tsx:60]: minor: when converting back to fiat does it use the correct formatting?

**Review by rolznz — APPROVED** [review]
utACK

File: components/DualCurrencyInput.tsx (hunk 1 above)
Comment (im-adithya) [reply components/DualCurrencyInput.tsx:60]: I tried to fix this using the `expo-localization` once for all, so that we can have the same type of decimal separator and digit grouping separators but there's an issue with Hermes not having good support for Intl in iOS which blocks this. I opened an [issue](https://github.com/getAlby/go/issues/305) to track this, but for now I'm merging as-is
