### PR TITLE
fix: improve linking

### LINKED ISSUE #83: [Bug] "Pay in Wallet" - Wallet won't load invoice correctly
Clicking "Pay in Wallet" and selecting Alby Go launches the wallet but then hangs, loading the invoice. Have to copy paste the invoice instead.

Same issue trying to pay a few invoices from different sources.

Screenshot_20240905-114641
Screenshot_20240905-114709

### LINKED ISSUE #128: lightning: and LNURL are being shown on the confirm payment and success pages when they should not
image

image

image

image

### PR DESCRIPTION
**Pull request by reneaaron**
# Improves scheme handling

## Improvements
 - Delay start of camera for link intents
 - Improve handling of human readable payment information (e.g. lightning:hello@getalby.com should display as hello@getalby.com)
 - Fixes #128
 - Fixes #83

## Testing (and for future reference)

To simulate opens during development:
```
npx uri-scheme open exp://127.0.0.1:8081/--/[LIGHTNING_ADDRESS] --android
npx uri-scheme open exp://127.0.0.1:8081/--/[LNURL] --android
npx uri-scheme open exp://127.0.0.1:8081/--/[BOLT11INVOICE] --android
```

### Test vectors
 - lightning:hello@getalby.com
 - bitcoin:bitcoinaddress?lightning=lnbc1...
 - lightning:lnurl
 - lightning:invoice

### CODE REVIEW

File: hooks/useHandleLinking.ts [hunk 1]
```diff
@@ -2,33 +2,33 @@ import * as Linking from "expo-linking";
 import { router, useRootNavigationState } from "expo-router";
 import React from "react";
 
-const SUPPORTED_SCHEMES = ["lightning:", "bitcoin:", "alby:"];
+// TODO: Remove exp://
+const SUPPORTED_SCHEMES = ["lightning:", "bitcoin:", "alby:", "exp:"];
```
Comment (reneaaron) [inline hooks/useHandleLinking.ts:6]:
```suggestion
const SUPPORTED_SCHEMES = ["lightning:", "bitcoin:", "alby:"];
```

File: hooks/useHandleLinking.ts [hunk 2]
```diff
@@ -2,33 +2,33 @@ import * as Linking from "expo-linking";
...
+        let currentUrl = url.startsWith(scheme + "//")
+          ? url.replace(scheme + "//", scheme)
+          : url;
 
-        // TODO: it should not always navigate to send,
-        // but that's the only linking functionality supported right now
-        router.dismissAll();
-        router.navigate({
+        // TODO: Remove, only for debugging purposes
+        currentUrl = currentUrl.replace("exp:127.0.0.1:8081/--/", "lightning:");
```
Comment (reneaaron) [inline hooks/useHandleLinking.ts:25]:
```suggestion
```

File: pages/send/Send.tsx [hunk 3]
```diff
@@ -23,10 +23,22 @@ export function Send() {
...
+  const [startScanning, setStartScanning] = React.useState(false);
 
+  // Delay starting the QR scanner if url has no valid payment info
   useEffect(() => {
     if (url) {
-      loadPayment(url);
+      (async () => {
+        try {
+          const result = await loadPayment(url);
+          setStartScanning(!result);
```
Comment (rolznz) [inline pages/send/Send.tsx:34]: maybe this could be simplified by returning if the result is ok, and always start scanning at the bottom of the function. Then there is no need for if/else.

**Review by rolznz — APPROVED** [review]
utACK, nice changes!

File: pages/send/Send.tsx (hunk 3 above)
Comment (reneaaron) [reply pages/send/Send.tsx:34]: Just tried, but I think that makes it harder to read / understand.
