### PR TITLE
fix: persist balance display mode

### LINKED ISSUE #200: Persist Balance Display Mode on Home Screen
If I set my balance display to be "****", when I restart Alby Go it is back to the Sats/USD display.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #200

Now we store a `balanceDisplayMode` field in app store and secure-storage

### CODE REVIEW

File: pages/Home.tsx [hunk 1]
```diff
@@ -55,12 +47,12 @@ export function Home() {
   };
 
   function switchBalanceState(): void {
-    if (balanceState === BalanceState.SATS) {
-      setBalanceState(BalanceState.FIAT);
-    } else if (balanceState === BalanceState.FIAT) {
-      setBalanceState(BalanceState.HIDDEN);
+    if (balanceDisplayMode === "sats") {
```
Comment (rolznz) [inline pages/Home.tsx:50]: minor: could use a `switch` here

**Review by rolznz — APPROVED** [review]
utACK

File: pages/Home.tsx (hunk 1 above)
Comment (im-adithya) [reply pages/Home.tsx]: Done
