### PR TITLE
fix: check for ln address and bolt11 before navigating to send

### LINKED ISSUE #162: Make findLnurl more consistent & add tests
Make `findLnurl` return a lightning address as well, currently it doesn't return hello@getalby.com when lightning:hello@getalby.com is passed.

Add some automated tests for different cases.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #162 and also an issue where scanning `alby:hello@getalby.com` QRs result in `Failed to decoide payment request errors`

### CODE REVIEW

File: lib/link.ts [hunk 1]
```diff
@@ -44,27 +45,48 @@ export const handleLink = async (url: string) => {
...
+    const bolt11Match = trimmedUrl.match(BOLT11_REGEX);
+    if (bolt11Match) {
+      const bolt11 = bolt11Match[1];
+      router.push({
+        pathname: "/send",
+        params: {
+          url: bolt11,
+        },
+      });
+    }
```
Comment (im-adithya) [inline lib/link.ts:89]: Should we redirect to Home if nothing matches with a flag to trigger an error here?
