### PR TITLE
fix: allow deleting last wallet

### LINKED ISSUE #118: Can't delete last wallet
I'm trying to delete my connections (having multiple wallets, on Android Alby Go), and all goes fine... but the last one doesnt' want to get deleted.

After "Delete wallet" it just comes back to wallets' list with the last one still standing with its NWC secret saved.

### PR DESCRIPTION
**Pull request by im-adithya**
Fixes #118

Also fixes Reset. Both will now redirect the user to the `/onboarding` screen.

### CODE REVIEW

**Review by reneaaron — APPROVED** [review]
tACK

File: lib/state/appStore.ts [hunk 1]
```diff
@@ -99,7 +99,15 @@ export const useAppStore = create<AppState>()((set, get) => {
   const removeCurrentWallet = () => {
     const wallets = [...get().wallets];
     if (wallets.length <= 1) {
-      // cannot delete last wallet
+      // set to initial wallet status
```
Comment (rolznz) [inline lib/state/appStore.ts:102]: I am not sure this check is needed or if we can actually just delete the whole `if`?

Comment (im-adithya) [reply lib/state/appStore.ts:102]: Wouldn't we need this check? We only do the below if it is the last wallet right?

Comment (rolznz) [reply lib/state/appStore.ts:102]: At the bottom is still does:
```
    get().setSelectedWalletId(0);
    set({
      wallets: wallets.filter((_, i) => i !== selectedWalletId),
    });
```

But I think there is actually a bug in the for loop - it will always not work if you try delete the wallet at the last index
